/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.MedsManager;
import Backend.SpeciesManager;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author HYSTOU
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() throws FileNotFoundException {
        initComponents();

        //Initialise Species Screen
        //1. Get list from backend
        //2. Create DefaultListModel 
        //3. Add list to model
        //4, Set model
        //Initialise xxxx Screen
        updateSpeciesList();
        updateMedsList();
    }

    public void updateSpeciesList() throws FileNotFoundException {
        //populating the species list
        String[] species = SpeciesManager.getSpeciesList();
        
        //Populate lists
        DefaultListModel speciesListModel = new DefaultListModel();
        for (int i = 0; i < species.length; i++) {
            speciesListModel.addElement(species[i]);

        }
        List_SPECIES_SpeciesList.setModel(speciesListModel);
        
        //Populate combo boxes
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel(species);
        ComboBox_MED_Species.setModel(comboBoxModel);
        ComboBox_CAL_Species.setModel(comboBoxModel);
    }

    public void updateMedsList() throws FileNotFoundException {
        //populating the species list
        String[] meds = MedsManager.getMedsList();
        DefaultListModel medsListModel = new DefaultListModel();
        for (int i = 0; i < meds.length; i++) {
            medsListModel.addElement(meds[i]);

        }
        List_MED_MedsList.setModel(medsListModel);
    }
    
    public void populateMedsSpeciesComboBox(String species) throws FileNotFoundException {

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane17 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        Button_MED_MedsDelete = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PasswordField_LOGIN_Name = new javax.swing.JPasswordField();
        LOGIN_PANE = new javax.swing.JPanel();
        Label_LOGIN_Name = new javax.swing.JLabel();
        Label_LOGIN_Password = new javax.swing.JLabel();
        TextField_LOGIN_Name = new javax.swing.JTextField();
        LOGOPlacment_LOGIN = new javax.swing.JTextField();
        LOCATION_TAB = new javax.swing.JTabbedPane();
        DOSAGE_CAL_PANE = new javax.swing.JPanel();
        Label_CAL_Speices = new javax.swing.JLabel();
        Label_CAL_Weight = new javax.swing.JLabel();
        Label_CAL_Medication = new javax.swing.JLabel();
        ComboBox_CAL_Species = new javax.swing.JComboBox<>();
        Button_CAL_Calculate = new javax.swing.JButton();
        TextField_CAL_Dosage = new javax.swing.JTextField();
        Label_CAL_Dosage = new javax.swing.JLabel();
        TextField_CAL_Weight = new javax.swing.JTextField();
        TextField_CAL_Medication = new javax.swing.JTextField();
        SPECIES_PANE = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        List_SPECIES_SpeciesList = new javax.swing.JList<>();
        Label_SPECIES_SpeciesList = new javax.swing.JLabel();
        Label_SPECIES_Name = new javax.swing.JLabel();
        TextField_SPECIES_Species = new javax.swing.JTextField();
        Button_SPECIES_Add = new javax.swing.JButton();
        Label_SPECIES_SelectDelete = new javax.swing.JLabel();
        Button_SPECIES_Delete = new javax.swing.JButton();
        MEDICATION_PANE = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        List_MED_MedsList = new javax.swing.JList<>();
        TextField_MED_MedName = new javax.swing.JTextField();
        TextField_MED_FormulaAdd = new javax.swing.JTextField();
        Button_MED_FormulaAdd = new javax.swing.JButton();
        Label_MED_FormulaAdd = new javax.swing.JLabel();
        Label_MED_MedName = new javax.swing.JLabel();
        Label_MED_FormulaGuide = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        TextArea_MED_FormulaGuide = new javax.swing.JTextArea();
        Label_MED_MedsList = new javax.swing.JLabel();
        Label_MED_Species = new javax.swing.JLabel();
        ComboBox_MED_Species = new javax.swing.JComboBox<>();
        Label_MED_SelectDelete = new javax.swing.JLabel();
        Button_MED_Delete = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jTree1);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");
        jTabbedPane3.addTab("Dosage Calulatoer", jLabel1);
        jTabbedPane3.addTab("tab2", jTabbedPane4);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("glllv.v;v.;';b'\n]");
        jScrollPane5.setViewportView(jTextArea3);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("s");
        jScrollPane4.setViewportView(jTextArea2);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane6.setViewportView(jTextArea4);

        jScrollPane7.setViewportView(jTextPane1);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane8.setViewportView(jTextArea5);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane11.setViewportView(jTextArea7);

        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jScrollPane14.setViewportView(jTextArea9);

        jLabel10.setText("jLabel10");

        jLabel11.setText("jLabel11");

        jButton2.setText("jButton2");

        jFormattedTextField1.setText("jFormattedTextField1");
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jFormattedTextField2.setText("jFormattedTextField2");

        jLabel8.setText("Select a Medicaton from the list then click the delete buttion to delete it");

        jScrollPane16.setViewportView(jTextPane2);

        jLabel7.setText("jLabel7");

        jTextArea1.setBackground(new java.awt.Color(251, 193, 110));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane9.setViewportView(jTextArea6);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane13.setViewportView(jTextArea8);

        jButton3.setText("jButton3");

        jTextField7.setText("jTextField7");

        jScrollPane17.setViewportView(jEditorPane1);

        Button_MED_MedsDelete.setText("DELETE");

        jTextField8.setText("jTextField8");

        jTextArea10.setColumns(20);
        jTextArea10.setRows(5);
        jScrollPane18.setViewportView(jTextArea10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        PasswordField_LOGIN_Name.setText("jPasswordField1");

        LOGIN_PANE.setBackground(new java.awt.Color(217, 217, 217));
        LOGIN_PANE.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null), null), null), null));

        Label_LOGIN_Name.setText("Name");

        Label_LOGIN_Password.setText("Password");

        LOGOPlacment_LOGIN.setText("LOGO");

        javax.swing.GroupLayout LOGIN_PANELayout = new javax.swing.GroupLayout(LOGIN_PANE);
        LOGIN_PANE.setLayout(LOGIN_PANELayout);
        LOGIN_PANELayout.setHorizontalGroup(
            LOGIN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGIN_PANELayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(LOGIN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LOGOPlacment_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LOGIN_PANELayout.createSequentialGroup()
                        .addGroup(LOGIN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Label_LOGIN_Name)
                            .addComponent(Label_LOGIN_Password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextField_LOGIN_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        LOGIN_PANELayout.setVerticalGroup(
            LOGIN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGIN_PANELayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(LOGIN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_LOGIN_Name)
                    .addComponent(TextField_LOGIN_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Label_LOGIN_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(LOGOPlacment_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LOCATION_TAB.setBackground(new java.awt.Color(217, 217, 217));
        LOCATION_TAB.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        LOCATION_TAB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOCATION_TABMouseClicked(evt);
            }
        });

        DOSAGE_CAL_PANE.setBackground(new java.awt.Color(217, 217, 217));
        DOSAGE_CAL_PANE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)));

        Label_CAL_Speices.setText("Species");

        Label_CAL_Weight.setText("Weight");

        Label_CAL_Medication.setText("Medication");

        ComboBox_CAL_Species.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_CAL_Species.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_CAL_SpeciesActionPerformed(evt);
            }
        });

        Button_CAL_Calculate.setText("CALCULATE");

        TextField_CAL_Dosage.setText("Final Calculation to show here");

        Label_CAL_Dosage.setText("Dosage");

        javax.swing.GroupLayout DOSAGE_CAL_PANELayout = new javax.swing.GroupLayout(DOSAGE_CAL_PANE);
        DOSAGE_CAL_PANE.setLayout(DOSAGE_CAL_PANELayout);
        DOSAGE_CAL_PANELayout.setHorizontalGroup(
            DOSAGE_CAL_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DOSAGE_CAL_PANELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_CAL_Calculate)
                .addGap(41, 41, 41))
            .addGroup(DOSAGE_CAL_PANELayout.createSequentialGroup()
                .addGroup(DOSAGE_CAL_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DOSAGE_CAL_PANELayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(DOSAGE_CAL_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_CAL_Speices)
                            .addComponent(Label_CAL_Weight)
                            .addComponent(Label_CAL_Medication))
                        .addGap(56, 56, 56)
                        .addGroup(DOSAGE_CAL_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_CAL_Medication, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_CAL_Weight, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_CAL_Species, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DOSAGE_CAL_PANELayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(DOSAGE_CAL_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_CAL_Dosage, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_CAL_Dosage, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        DOSAGE_CAL_PANELayout.setVerticalGroup(
            DOSAGE_CAL_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DOSAGE_CAL_PANELayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(DOSAGE_CAL_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_CAL_Speices)
                    .addComponent(ComboBox_CAL_Species, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(DOSAGE_CAL_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_CAL_Weight)
                    .addComponent(TextField_CAL_Weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(DOSAGE_CAL_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_CAL_Medication)
                    .addComponent(TextField_CAL_Medication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(Button_CAL_Calculate)
                .addGap(9, 9, 9)
                .addComponent(Label_CAL_Dosage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_CAL_Dosage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        LOCATION_TAB.addTab("Dosage Calculator", DOSAGE_CAL_PANE);

        SPECIES_PANE.setBackground(new java.awt.Color(217, 217, 217));

        List_SPECIES_SpeciesList.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        List_SPECIES_SpeciesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane12.setViewportView(List_SPECIES_SpeciesList);

        Label_SPECIES_SpeciesList.setText("Species");

        Label_SPECIES_Name.setText("Name");

        Button_SPECIES_Add.setText("ADD");
        Button_SPECIES_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SPECIES_AddActionPerformed(evt);
            }
        });

        Label_SPECIES_SelectDelete.setText("Select Species from list to Delete");

        Button_SPECIES_Delete.setText("DELETE");
        Button_SPECIES_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SPECIES_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SPECIES_PANELayout = new javax.swing.GroupLayout(SPECIES_PANE);
        SPECIES_PANE.setLayout(SPECIES_PANELayout);
        SPECIES_PANELayout.setHorizontalGroup(
            SPECIES_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SPECIES_PANELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SPECIES_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SPECIES_PANELayout.createSequentialGroup()
                        .addComponent(Label_SPECIES_SpeciesList)
                        .addGap(26, 26, 26))
                    .addGroup(SPECIES_PANELayout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(SPECIES_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SPECIES_PANELayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button_SPECIES_Add)
                                .addGap(118, 118, 118))
                            .addGroup(SPECIES_PANELayout.createSequentialGroup()
                                .addGroup(SPECIES_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SPECIES_PANELayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(Label_SPECIES_Name)
                                        .addGap(34, 34, 34)
                                        .addComponent(TextField_SPECIES_Species, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(SPECIES_PANELayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Label_SPECIES_SelectDelete)
                                        .addGap(18, 18, 18)
                                        .addComponent(Button_SPECIES_Delete)))
                                .addGap(0, 81, Short.MAX_VALUE))))))
        );
        SPECIES_PANELayout.setVerticalGroup(
            SPECIES_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SPECIES_PANELayout.createSequentialGroup()
                .addGroup(SPECIES_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SPECIES_PANELayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(SPECIES_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextField_SPECIES_Species, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_SPECIES_Name))
                        .addGap(34, 34, 34)
                        .addComponent(Button_SPECIES_Add)
                        .addGap(50, 50, 50)
                        .addGroup(SPECIES_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_SPECIES_SelectDelete)
                            .addComponent(Button_SPECIES_Delete)))
                    .addGroup(SPECIES_PANELayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(Label_SPECIES_SpeciesList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        LOCATION_TAB.addTab("Species ", SPECIES_PANE);

        MEDICATION_PANE.setBackground(new java.awt.Color(217, 217, 217));

        List_MED_MedsList.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        List_MED_MedsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(List_MED_MedsList);

        TextField_MED_MedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_MED_MedNameActionPerformed(evt);
            }
        });

        Button_MED_FormulaAdd.setText("ADD");
        Button_MED_FormulaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MED_FormulaAddActionPerformed(evt);
            }
        });

        Label_MED_FormulaAdd.setText("Formula");

        Label_MED_MedName.setText("Medication Name");

        Label_MED_FormulaGuide.setText("Formula Guide");

        TextArea_MED_FormulaGuide.setEditable(false);
        TextArea_MED_FormulaGuide.setColumns(20);
        TextArea_MED_FormulaGuide.setRows(5);
        jScrollPane15.setViewportView(TextArea_MED_FormulaGuide);

        Label_MED_MedsList.setBackground(new java.awt.Color(251, 193, 110));
        Label_MED_MedsList.setText("Medications");

        Label_MED_Species.setText("Species");

        ComboBox_MED_Species.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Label_MED_SelectDelete.setText("Select Medication from list to Delete");

        Button_MED_Delete.setText("DELETE");
        Button_MED_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MED_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MEDICATION_PANELayout = new javax.swing.GroupLayout(MEDICATION_PANE);
        MEDICATION_PANE.setLayout(MEDICATION_PANELayout);
        MEDICATION_PANELayout.setHorizontalGroup(
            MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                        .addComponent(Label_MED_MedsList)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                                .addGroup(MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Label_MED_MedName))
                                    .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(TextField_MED_MedName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(70, 70, 70)
                                .addGroup(MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBox_MED_Species, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_MED_Species))
                                .addGap(0, 63, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MEDICATION_PANELayout.createSequentialGroup()
                                .addGroup(MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Label_MED_SelectDelete))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MEDICATION_PANELayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label_MED_FormulaGuide)
                                            .addComponent(jScrollPane15))))
                                .addGroup(MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label_MED_FormulaAdd)
                                            .addComponent(TextField_MED_FormulaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MEDICATION_PANELayout.createSequentialGroup()
                                                .addComponent(Button_MED_FormulaAdd)
                                                .addGap(40, 40, 40))))
                                    .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(Button_MED_Delete)))))))
                .addContainerGap())
        );
        MEDICATION_PANELayout.setVerticalGroup(
            MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Label_MED_MedsList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                        .addGroup(MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                                .addGroup(MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_MED_SelectDelete)
                                    .addComponent(Button_MED_Delete))
                                .addGap(31, 31, 31)
                                .addComponent(Label_MED_MedName))
                            .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(Label_MED_Species)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_MED_MedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_MED_Species, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label_MED_FormulaGuide)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MEDICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MEDICATION_PANELayout.createSequentialGroup()
                                .addComponent(Label_MED_FormulaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(TextField_MED_FormulaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button_MED_FormulaAdd))
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        LOCATION_TAB.addTab("Medication ", MEDICATION_PANE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LOCATION_TAB)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOCATION_TAB)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOCATION_TABMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOCATION_TABMouseClicked
        //LOCATION_TAB.setBackground(Color.red);
    
    }//GEN-LAST:event_LOCATION_TABMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ComboBox_CAL_SpeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_CAL_SpeciesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_CAL_SpeciesActionPerformed

    private void Button_MED_FormulaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MED_FormulaAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_MED_FormulaAddActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void Button_MED_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MED_DeleteActionPerformed
        try {
            String selectedMeds = List_MED_MedsList.getSelectedValue();
            MedsManager.deleteMeds(selectedMeds);
            updateMedsList();
        } catch (Exception ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_MED_DeleteActionPerformed

    private void Button_SPECIES_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SPECIES_DeleteActionPerformed
        try {
            // get stuff from frontend
            String seletedSpecies = List_SPECIES_SpeciesList.getSelectedValue();
            // send to backend
            SpeciesManager.deleteSpecies(seletedSpecies);
            // updata frontend
            updateSpeciesList();

        } catch (Exception ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
        {

        }
    }//GEN-LAST:event_Button_SPECIES_DeleteActionPerformed

    private void Button_SPECIES_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SPECIES_AddActionPerformed

        try {
            // get stuff from frontend
            String NewSpecies = TextField_SPECIES_Species.getText();
            // send to backend
            SpeciesManager.addSpecies(NewSpecies);
            // updata frontend
            updateSpeciesList();

        } catch (IOException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Button_SPECIES_AddActionPerformed

    private void TextField_MED_MedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_MED_MedNameActionPerformed
        try {
            // get stuff from frontend
            String NewMeds = TextField_MED_MedName.getText();
            // send to backend
            MedsManager.addMeds(NewMeds);
            // updata frontend
            updateMedsList();

        } catch (IOException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }

    
    }//GEN-LAST:event_TextField_MED_MedNameActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UI().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(UI

.class
.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_CAL_Calculate;
    private javax.swing.JButton Button_MED_Delete;
    private javax.swing.JButton Button_MED_FormulaAdd;
    private javax.swing.JButton Button_MED_MedsDelete;
    private javax.swing.JButton Button_SPECIES_Add;
    private javax.swing.JButton Button_SPECIES_Delete;
    private javax.swing.JComboBox<String> ComboBox_CAL_Species;
    private javax.swing.JComboBox<String> ComboBox_MED_Species;
    private javax.swing.JPanel DOSAGE_CAL_PANE;
    private javax.swing.JTabbedPane LOCATION_TAB;
    private javax.swing.JPanel LOGIN_PANE;
    private javax.swing.JTextField LOGOPlacment_LOGIN;
    private javax.swing.JLabel Label_CAL_Dosage;
    private javax.swing.JLabel Label_CAL_Medication;
    private javax.swing.JLabel Label_CAL_Speices;
    private javax.swing.JLabel Label_CAL_Weight;
    private javax.swing.JLabel Label_LOGIN_Name;
    private javax.swing.JLabel Label_LOGIN_Password;
    private javax.swing.JLabel Label_MED_FormulaAdd;
    private javax.swing.JLabel Label_MED_FormulaGuide;
    private javax.swing.JLabel Label_MED_MedName;
    private javax.swing.JLabel Label_MED_MedsList;
    private javax.swing.JLabel Label_MED_SelectDelete;
    private javax.swing.JLabel Label_MED_Species;
    private javax.swing.JLabel Label_SPECIES_Name;
    private javax.swing.JLabel Label_SPECIES_SelectDelete;
    private javax.swing.JLabel Label_SPECIES_SpeciesList;
    private javax.swing.JList<String> List_MED_MedsList;
    private javax.swing.JList<String> List_SPECIES_SpeciesList;
    private javax.swing.JPanel MEDICATION_PANE;
    private javax.swing.JPasswordField PasswordField_LOGIN_Name;
    private javax.swing.JPanel SPECIES_PANE;
    private javax.swing.JTextArea TextArea_MED_FormulaGuide;
    private javax.swing.JTextField TextField_CAL_Dosage;
    private javax.swing.JTextField TextField_CAL_Medication;
    private javax.swing.JTextField TextField_CAL_Weight;
    private javax.swing.JTextField TextField_LOGIN_Name;
    private javax.swing.JTextField TextField_MED_FormulaAdd;
    private javax.swing.JTextField TextField_MED_MedName;
    private javax.swing.JTextField TextField_SPECIES_Species;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
